server:
  session-timeout: 10
  tomcat:
    max-threads: 20
    uri-encoding: UTF-8
    max-http-header-size: 102400
    maxParameterCount: 100000
  logging:
    config: classpath*:logback.xml
  servlet:
    context-path: /boot-demo
    session:
      cookie:
        name: BOOT-SESSIONID  # replace JSESSIONID

spring:
  profiles:
    active: dev
    include: rpc
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    name: boot-demo
    url: jdbc:mysql://localhost:3306/boot-demo?characterEncoding=utf-8
    username: boot_demo_rw
    password: 5c9C27omdA!d%^8v
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    from: dev@example.com
    to: receiver@example.com
    cc:
    title: Example Email
    host: proxy.email-example.com
    properties:
      mail:
        smtp:
          timeout: 25000

mybatis:
  typeAliasesPackage: com.boot.dao.model
  mapperLocations: classpath*:mappers/**Mapper.xml
